### ISSUE TITLE
Comments 2/20

### ISSUE THREAD

**Issue by germonprez** [Amer2483/ISQA3420-#10]
DFD 

1) Scanner is not a clear name. Provide more detail 
2) It is not clear how the Manager is getting the L&V results via the L&V DB
3) The developer needs to be able to query the L&V DB for results 
4) Why is Policy Information coming back from the Edit Process? 

UC1

1) Why is the Project Owner is this? We have not discussed this person 
2) You need to format this more clearly.

**Comment by Amer2483** [comment]
Changes Done
