### ISSUE TITLE
DFD Comments 2/20

### ISSUE THREAD

**Issue by germonprez** [Amer2483/ISQA3420-#12]
1) Are these the same dataflow? Should Policy Request be Policy Updates? 

<img width="114" alt="screen shot 2017-02-20 at 6 09 54 pm" src="https://cloud.githubusercontent.com/assets/656208/23145918/e44d7b9e-f797-11e6-968d-d630a9308849.png">

2) The Developer needs to be able to query the db like the manager: 

<img width="221" alt="screen shot 2017-02-20 at 6 10 56 pm" src="https://cloud.githubusercontent.com/assets/656208/23145938/fc64d47a-f797-11e6-8588-53b429b04e80.png">

**Comment by Amer2483** [comment]
changes done
