### ISSUE TITLE
Repo Comments

### ISSUE THREAD

**Issue by germonprez** [Amer2483/ISQA3420-#15]
ES

1) Sentences like: "dto open source components" have typos. 

software.Such system
databases like NIIST and OSS 

DFD

1) It is simply too blurry. You must get a sharper image. If you turn this in, you will lose points. 

a) Request Information and Retrieve Information are too vague of names. You need to be more specific
b) From Request Information, there needs to be a dataflow that actually makes the request 
c) Some Dataflows (like Policy Request) need better names. Edited Policy? 

Use Cases 

1) UC2: Data should also be sent to DB as a main success scenario
2) UC3: The Goal in Context should be for the Manager, not the Developer 
3) UC3: Why does the L&V database need to be updated for this UC? 
4) UC3: The Developer does not send information to the Manager - check your DFD

**Comment by Amer2483** [comment]
changes done
