### ISSUE TITLE
DFD Comments

### ISSUE THREAD

**Issue by germonprez** [Amer2483/ISQA3420-#19]
1) Request/Result is far too vague. Be more specific. 
2) Why is it Retrieve Software Information when you are retrieving policies? 
3) Is Scanner Result the same as License/Scanner Result? I believe they are and should be named the same thing. 

These are very minor details but things that you should be attentive to. Go through your DFD very carefully as this list is only some of the problems. 

Overall, the structure looks fair but these minor issues will prove to be a problem.

**Comment by Amer2483** [comment]
CHANGES DONE
