### ISSUE TITLE
use case comments

### ISSUE THREAD

**Issue by germonprez** [Amer2483/ISQA3420-#20]
1) Check your formatting. Things like Developer and Manager should not be the same level as the top level headers like Preconditions. 

2) Why is the developer part of the policy process? 

These are not the complete set of comments. Like the DFD, you have to be very careful as to how you construct your use cases. You have to have attention to detail such that the use cases align perfectly with your DFD>

**Comment by Amer2483** [comment]
CHANGES DONE
