### ISSUE TITLE
DFD Issues Feb 17

### ISSUE THREAD

**Issue by germonprez** [Amer2483/ISQA3420-#8]
Comments: 

1) The developer does not need to access policy

<img width="164" alt="screen shot 2017-02-17 at 10 02 25 am" src="https://cloud.githubusercontent.com/assets/656208/23077171/4548c158-f4f8-11e6-9f45-e9a00a3d5058.png">

2) These dataflows are not needed: 

<img width="93" alt="screen shot 2017-02-17 at 10 03 38 am" src="https://cloud.githubusercontent.com/assets/656208/23077203/67f912ac-f4f8-11e6-8d7b-bf53d949bf50.png">

<img width="262" alt="screen shot 2017-02-17 at 10 04 16 am" src="https://cloud.githubusercontent.com/assets/656208/23077218/77af7eb6-f4f8-11e6-87bf-e88cb3ae097b.png">

**Comment by germonprez** [comment]
Also, you are going to have to get a clearer picture. The blurry picture is bad.

**Comment by Amer2483** [comment]
CHANGES DONE
